### ISSUE TITLE
Correctly parsing of incorrect ETXINF tag

### ISSUE THREAD

**Issue by ycherniavskyi** [NimitzDEV/m3u8-file-parser#10]
Currently during parsing next ETXINF tag - `#EXTINF:6.000000`, next error thrown:
```
(node:53592) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'charCodeAt' of undefined
    at Object.extinf [as parser] (/Users/u/p/node_modules/m3u8-file-parser/src/parser/extinf.js:36:24)
    at M3U8FileParser.invokeParser (/Users/u/p/node_modules/m3u8-file-parser/src/reader.js:77:46)
    at M3U8FileParser.read (/Users/u/p/node_modules/m3u8-file-parser/src/reader.js:59:12)
    at httpsGet.then (/Users/u/p/t.js:51:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

And yes, this error is _correct_ because RFC says that there must be a comma at the end. But unfortunately, there is not, and I am sure that the provider of this m3u8 file will ignore my argument about standard inconsistent.
Is it possible to add durability to ETXINF tag parsing, when it meat not _fully_ correct ETXINF tag?

**Comment by NimitzDEV** [comment]
Could you provide more sample from your M3U8 file, I will take a look during this weekend.

**Comment by ycherniavskyi** [comment]
Yes sure. Actually this is `playlist.m3u8` file for one of the available formats in `master.m3u8` file which was received from Vimeo video config in hsl format (so I think you uderstand why I said that rpovided of this incorrect m3u8 file will not fix it 😊).
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="chop/segment-0.mp4"
#EXTINF:6.000000
chop/segment-1.m4s
#EXTINF:6.000000
chop/segment-2.m4s
#EXTINF:6.000000
chop/segment-3.m4s
#EXTINF:6.000000
chop/segment-4.m4s
#EXTINF:6.000000
chop/segment-5.m4s
#EXTINF:6.000000
chop/segment-6.m4s
#EXTINF:6.000000
chop/segment-7.m4s
#EXTINF:6.000000
chop/segment-8.m4s
#EXTINF:6.000000
chop/segment-9.m4s
#EXTINF:6.000000
chop/segment-10.m4s
#EXTINF:6.000000
chop/segment-11.m4s
#EXTINF:6.000000
chop/segment-12.m4s
#EXTINF:6.000000
chop/segment-13.m4s
#EXTINF:6.000000
chop/segment-14.m4s
#EXTINF:6.000000
chop/segment-15.m4s
#EXTINF:6.000000
chop/segment-16.m4s
#EXTINF:6.000000
chop/segment-17.m4s
#EXTINF:6.000000
chop/segment-18.m4s
#EXTINF:6.000000
chop/segment-19.m4s
#EXTINF:6.000000
chop/segment-20.m4s
#EXTINF:6.000000
chop/segment-21.m4s
#EXTINF:6.000000
chop/segment-22.m4s
#EXTINF:6.000000
chop/segment-23.m4s
#EXTINF:6.000000
chop/segment-24.m4s
#EXTINF:6.000000
chop/segment-25.m4s
#EXTINF:6.000000
chop/segment-26.m4s
#EXTINF:6.000000
chop/segment-27.m4s
#EXTINF:6.000000
chop/segment-28.m4s
#EXTINF:6.000000
chop/segment-29.m4s
#EXTINF:6.000000
chop/segment-30.m4s
#EXTINF:6.000000
chop/segment-31.m4s
#EXTINF:6.000000
chop/segment-32.m4s
#EXTINF:6.000000
chop/segment-33.m4s
#EXTINF:6.000000
chop/segment-34.m4s
#EXTINF:6.000000
chop/segment-35.m4s
#EXTINF:6.000000
chop/segment-36.m4s
#EXTINF:6.000000
chop/segment-37.m4s
#EXTINF:6.000000
chop/segment-38.m4s
#EXTINF:6.000000
chop/segment-39.m4s
#EXTINF:6.000000
chop/segment-40.m4s
#EXTINF:6.000000
chop/segment-41.m4s
#EXTINF:2.480000
chop/segment-42.m4s
#EXT-X-ENDLIST
```

**Comment by NimitzDEV** [comment]
Hi @ycherniavskyi , please try to install version 0.2.3 and see if this issue was fixed.

**Comment by ycherniavskyi** [comment]
@NimitzDEV version 0.2.3 fixed the issue, thanks.
